--drop index role_pk;
--drop index user_pk
--Drop table role;
--drop table user;
create table role (
    id  INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
    name VARCHAR(15) NOT NULL,
    typeid INTEGER not null,
	CONSTRAINT role_pk PRIMARY KEY (id)
);
create table user (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
    username varchar(50) not null,
    password varchar(250) not null,
    password_confirm  varchar(250),
    typeid INTEGER not null,
	CONSTRAINT user_pk PRIMARY KEY (id)
);
create sequence hibernate_sequence;

insert into role(name, typeid) values('ADMIN',5);
insert into role(name, typeid) values('REMOVE_USER',5);
insert into role(name, typeid) values('MNAGER',5)
commit;

